import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { checkout } from "../checkout"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Physical NFTs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Buy my phsyical NFTs</h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Image
              src="/images/enjoyinglife.jpeg"
              alt="enjoying life"
              width={400}
              height={400}
            />
            <p>Very expensive art piece 1</p>
            <button onClick={(() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1LtcuKKHeBrFfwHueXwELDtF",
                    quantity: 1,
                  }
                ]
              });
            })}>buy this swag</button>
          </div>
          <div className={styles.card}>
            <Image
              src="/images/filter.JPG"
              alt="enjoying life"
              width={400}
              height={400}
            />
            <p>Very expensive art piece 2</p>
          </div>
        </div>
      </main>
    </div>
  );
}
